# Generated by Django 2.2.14 on 2020-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fffffgfhgfhgfh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgfhgjfhgfhgf', models.BigIntegerField()),
            ],
        ),
    ]
